// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1wyPqjYn543DivSbrcmvkg4DczEmLrro',
    appId: '1:755814355996:web:e9ce556517aa4b2350fbd9',
    messagingSenderId: '755814355996',
    projectId: 'astra-ca2db',
    authDomain: 'astra-ca2db.firebaseapp.com',
    storageBucket: 'astra-ca2db.firebasestorage.app',
    measurementId: 'G-X6FG6T9TV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCzDyjbFMUSIXjoGJuKdJx_w7AOJBZsM',
    appId: '1:755814355996:android:f3baa75be01a15b750fbd9',
    messagingSenderId: '755814355996',
    projectId: 'astra-ca2db',
    storageBucket: 'astra-ca2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrwSaaFIofiXy7VKoJQSkEjWBSJ5kviQ',
    appId: '1:755814355996:ios:16e2d7c052c89dbd50fbd9',
    messagingSenderId: '755814355996',
    projectId: 'astra-ca2db',
    storageBucket: 'astra-ca2db.firebasestorage.app',
    iosBundleId: 'com.example.virtualAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrwSaaFIofiXy7VKoJQSkEjWBSJ5kviQ',
    appId: '1:755814355996:ios:16e2d7c052c89dbd50fbd9',
    messagingSenderId: '755814355996',
    projectId: 'astra-ca2db',
    storageBucket: 'astra-ca2db.firebasestorage.app',
    iosBundleId: 'com.example.virtualAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1wyPqjYn543DivSbrcmvkg4DczEmLrro',
    appId: '1:755814355996:web:67519342e3cb491650fbd9',
    messagingSenderId: '755814355996',
    projectId: 'astra-ca2db',
    authDomain: 'astra-ca2db.firebaseapp.com',
    storageBucket: 'astra-ca2db.firebasestorage.app',
    measurementId: 'G-98XBHNSDSZ',
  );
}
